### ISSUE TITLE
Compartmentalising Unit Testing

### ISSUE THREAD

**Issue by RootDevil** [midmandle/PERTY#15]
In order to keep testing organised and readable, ensure unit tests for specific classes are implemented in a separate file.  
- For example, the perty.py and taskList.py classes are to be tested in UnitTest_pert.py and UnitTest_taskList.py respectively.
- Make sure tests are written prior to any implementation.

**Comment by midmandle** [comment]
So we agree that each .py file which logically groups functionality should have its own test suite?

**Comment by midmandle** [comment]
Can we close this issue following the approval of the pull request I made earlier please @RootDevil?

**Comment by midmandle** [comment]
@RootDevil can you close this? I've made the changes to the unit testing files such that things can be separated out. It'd be good to get this cleared.
