### ISSUE TITLE
Configure GitHub

### ISSUE THREAD

**Issue by midmandle** [midmandle/PERTY#2]
Additional time needs to be spent to implement correct configuration of the GitHub settings/access/permissions. It's not set up correctly yet.

**Comment by midmandle** [comment]
I have restructured the file org in the master branch but I'm not sure I'm happy with it.

@RootDevil and @aakasht05 does this make sense?

**Comment by midmandle** [comment]
Some discussion is needed here with regards to a few administrative details @RootDevil @aakasht05.

**Comment by midmandle** [comment]
@RootDevil @aakasht05 last chance on this one. If we have any changes to make to the way we are using GitHub speak up now! I'm gonna close/freeze this issue for a good while now if there is no comment on if we need to change the setup of the repo.

You've got 24 hours then it's getting closed and I'm gonna put a freeze on any restructuring of the GitHub setup.

**Comment by RootDevil** [comment]
All seems fine to me.  Although, is there a better way to communicate comments or changes than via email?

**Comment by midmandle** [comment]
Hmm, I was thinking this. I think for formal commits/changes/merges then GitHub is the best way to do things. It would be done this way using regular Git anyway as it's just part of the process of using Git as source code management solution. I do think general communication about things could be done better. 

We can stick with FB messenger for now but perhaps we should consider making a Slack channel for dedicated development conversations?

**Comment by RootDevil** [comment]
I would agree with that @midmandle.  FB is a bit messy so Slack would be better.  It is sometimes very easy to lose track of development which is why we need to prioritise a clean communication channel.

**Comment by midmandle** [comment]
OK, I'll get on this today then. I'll update you when it's sorted.

**Comment by midmandle** [comment]
Just to be comprehensive, we now have a Slack channel (perty-group). Link on the Wiki page.

**Comment by midmandle** [comment]
I think we need to consider using branching in a different way... It feels wrong the way we are doing it. Kind of like it lacks cohesion. 

I wonder if it would be better to start using branches for specific tasks rather than individual working spaces. It would be far more collaborative because we would all be working on similar issues/releases/features and would be made aware of any changes. It might mean we would need to communicate a bit better but that's why we now have Slack.

**Comment by RootDevil** [comment]
Yes, I was thinking this.  We've not properly defined what each other's tasks/aims are, so people are working on random stuff hoping it will all meet together in the middle.

**Comment by midmandle** [comment]
Ok, I think we both see the same problem.

If we change to start working with branches as "release/feature" branches instead of private spaces per user we need to step up our organisation. It will mean having daily meetings to keep track of where each of us is at and some planning before making each new feature/release branch.

Can we commit to that (pun intended :P)? Also, we would genuinely need to commit all of the latest changes to PERTY_py from each of our private branches and then close each of the private branches before we go any further with development.

**Comment by RootDevil** [comment]
Ok, we should do that.  Tell me when to commit to PERTY_py.

**Comment by midmandle** [comment]
Well I just pushed my latest commits so as soon as you have committed your lates changes to your branch let me know and we will start the merge to PERTY_py.

**Comment by midmandle** [comment]
Ok, so the private_<name> branches have been merged to PERTY_py and removed. The new "feature/release" branch is called prototype and is being tracked in ZenHub under the release name "PERTY_py Prototype".

Unless we have any other changes to make, I'm going to close this issue.

Last chance.

**Comment by midmandle** [comment]
Issue closed for now. Raise a new issue if there are any problems.
