### ISSUE TITLE
Decide on best in-memory collection to use of Task objects in Python

### ISSUE THREAD

**Issue by midmandle** [midmandle/PERTY#6]

**Comment by midmandle** [comment]
@RootDevil and I decided we would use a List for now and update it when it becomes more relevant.

**Comment by midmandle** [comment]
I'm going to close this issue for now and open it up when it becomes a problem again. @aakasht05  last chance to give your opinion on this!

I'm gonna close this tomorrow if no one has any more input to the topic.

**Comment by RootDevil** [comment]
I don't have any opinion on this for now.  We should move ahead with a list based solution.  I'm currently working on some sorting functions in tasklist.py so I will inform you if any issues arise.

**Comment by midmandle** [comment]
Ok, this is getting closed. We shouldn't need to discuss this for some time until it becomes a relevant problem.
